### ISSUE TITLE
Suggestions/Request:

### ISSUE THREAD

**Issue by nsgithub22** [jinshen1983/hilites.today#12]
Hi Jinshen,
Awesome work on your hilites man! Very helpful. Thanks a ton!
I don't know much about the technicalities and far from a anything coding. However, I just a have a suggestion where if you could add a export data in csv or excel format for the summary, it will be nice to see the trend on our own in a excel sheet. 
Thanks

**Comment by jinshen-cn** [comment]
Close this one as it is duplicated to #11
