### ISSUE TITLE
Suggestion: RFE to main dashboard

### ISSUE THREAD

**Issue by ruzzzz6312** [jinshen1983/hilites.today#13]
Thanks for all you are doing.
It would be great to see RFE qty on the main dashboard, example attached

<img width="518" alt="Screen Shot 2022-08-11 at 12 49 37 PM" src="https://user-images.githubusercontent.com/23564850/184226967-a0e2a352-6bd7-4ce9-850c-7cfd288f2762.png">
.

**Comment by jinshen-cn** [comment]
Thanks for the suggestion.

Will add this ask to back log.

**Comment by jinshen-cn** [comment]
Added RFE to snapshot
