### ISSUE TITLE
New parameters filters for Query View

### ISSUE THREAD

**Issue by bertolini10** [jinshen1983/hilites.today#14]
Hi @jinshen1983.

I suggest putting new parameters in the query view (https://hilites.today/uscis_cases/search)  and (https://hilites.today/api/v1/uscis/query) endpoint. 

The new parameters are **case_type** and **center**.

With this, I suppose you can increase the maximum range to **5000** with no performance loss. 
I think that is important to see a list of all cases, related to the graph in the insights view (https://hilites.today/uscis_cases/insights)

What do you think?

**Comment by jinshen-cn** [comment]
the query is to scrape the USCIS webpage. so, no matter what parameters there, the performance is the same. Because the filter only happens after the scraping is done.

Maybe I can switch the query to query the existing data in the database, other than scrape the USCIS in real time.

**Comment by bertolini10** [comment]
OK, understood. I thought that query was over your own database. 
Is essential to keep the query view to scrape USCIS.

But, if you have time, creating a new view, over your own database, with various filters, will be great.

Is up to you,

**Comment by jinshen-cn** [comment]
And an offline query that queries the stored data.

**Comment by bertolini10** [comment]
thanks.
