### ISSUE TITLE
Add a column of last 7 or 15 days approval numbers or rate in the Summary

### ISSUE THREAD

**Issue by jinshen-cn** [jinshen1983/hilites.today#3]
One suggestion I had was to add a column of last 7 or 15 days approval numbers or rate in the Summary for every series range. That will provide indication to the user on which series USCIS is currently focusing on.

Raised by [all4PERM](https://www.trackitt.com/member/all4PERM)
Original Link from Trackitt

https://www.trackitt.com/usa-discussion-forums/i485-eb/2242906407/sn/1/user/421835/page/last_page#:~:text=One%20suggestion%20I%20had%20was%20to%20add%20a%20column%20of%20last%207%20or%2015%20days%20approval%20numbers%20or%20rate%20in%20the%20Summary%20for%20every%20series%20range.%20That%20will%20provide%20indication%20to%20the%20user%20on%20which%20series%20USCIS%20is%20currently%20focusing%20on

**Comment by jinshen1983** [comment]
Added approvals in the last 7days.

**Comment by jinshen-cn** [comment]
Added approvals in the last 7days, 14days, and 28dats.
