### ISSUE TITLE
stats of a cohort

### ISSUE THREAD

**Issue by jinshen-cn** [jinshen1983/hilites.today#4]
One question for you - is there a way within Hilites to follow a cohort? for example - of the people who were transferred to NBC in April, how many were approved, RFE, etc.?

Raised by [username9](https://www.trackitt.com/member/username9)

Original link from Trackitt
https://www.trackitt.com/usa-discussion-forums/i485-eb/2242906407/sn/1/user/421835/page/last_page#:~:text=one%20question%20for%20you%20-%20is%20there%20a%20way%20within%20hilites%20to%20follow%20a%20cohort%3F%20for%20example%20-%20of%20the%20people%20who%20were%20transferred%20to%20nbc%20in%20april%2C%20how%20many%20were%20approved%2C%20rfe%2C%20etc.%3F

**Comment by SharmaA10** [comment]
I second this suggestion. This would be great to have!

**Comment by SharmaA10** [comment]
Just curious how you are thinking about this one? 

In my opinion, you might be able to accommodate it either within the Query tab (ideal) or within the dashboard tab. 

Query Tab: (ideal but requires more UI changes)
Create a sub-tab to differentiate between Case query and Cohort query.
When a user clicks on Cohort query - they can select one data parameter (ex. received date, transfer date, approved date) and then select multiple dates to see the frequency distribution.

Dashboard Tab (requires less UI changes) 
You can add an additional filter for cohorts (similar to case range) where users can select a single condition: example - Show dashboard for cases where Case Center = TSC, Case Type = I-485, Case Status = All, range key = XXX=YYY, and NEW FILTER > Transfer date = MM/DD/YY - MM/DD/YY. Would be good to show a frequency distribution to summarize data here and make it more powerful.

Thoughts?

**Comment by jinshen-cn** [comment]
I added a new page for the cohort dashboard which is focusing on transferred cases.
https://hilites.today/uscis_cases/cohort

**Comment by SharmaA10** [comment]
Thanks! I tried it out and it seems to have 1 shortcoming.

For example, if I view dashboard for all April transfers for Nebraska_SC, it stops the dashboard at the end of my time range. In my opinion, the dashboard should continue to present date. In the same example, the april transfer cohort will start seeing approvals in May/June but the dashboard stops at the end of the cohort date range.

Thanks in advance!

**Comment by jinshen-cn** [comment]
Hi @SharmaA10 

I didn't quite get your question.
The date on this page is only the transferred date.
The chart shows the status of the cases up to date. For example, when you filter data on the date 04/01/2022, the dataset is all the cases that were transferred on 04/01/2022. And the chart shows the current status distribution of that dataset up to date today.

**Comment by jinshen-cn** [comment]
I added a second line chart to show the approval pace.
