### ISSUE TITLE
FY20 Data

### ISSUE THREAD

**Issue by Nirvana1986** [jinshen1983/hilites.today#6]
Hey Jinshen,
It will be great if you can add FY20 data to the hilites Dashboard. There are a ton of cases like mine that are also pending and it would be great to know if any movement is happening on those.

**Comment by jinshen-cn** [comment]
I started running crawler for FY20. Please be aware at this moment I only crawl the cases sent to the service center in FY20.

**Comment by Nirvana1986** [comment]
Awesome! You are best!

Wow the FY20 stats look worse than FY21 and FY22 🙁.

Thank you for all you do!

Regards,
Rishit
